
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Desktop
 */
@SuppressWarnings("serial")
public class Library extends javax.swing.JFrame {

    /**
     * Creates new form Library
     */
    public Library() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ADD = new javax.swing.JFrame();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        addInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DISPLAY = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        REMOVE = new javax.swing.JFrame();
        RemoveBook = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        SORT = new javax.swing.JFrame();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        ADD.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ADD.setMinimumSize(new java.awt.Dimension(700, 250));
        ADD.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        exit.setText("Exit");
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        ADD.getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 110, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Type The Book You Want To Add");
        jLabel6.setToolTipText("");
        ADD.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 60));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(204, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        add.setText("Add");
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        ADD.getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, 60));

        addInput.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        addInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInputActionPerformed(evt);
            }
        });
        ADD.getContentPane().add(addInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 450, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        jLabel7.setText("jLabel1");
        ADD.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -320, 1360, 650));

        DISPLAY.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Registered Books");
        jLabel8.setToolTipText("");
        DISPLAY.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 70));

        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton4.setText("Exit");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        DISPLAY.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, 50));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title"
            }
        ));
        jScrollPane2.setViewportView(Table);

        DISPLAY.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 400, 280));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        jLabel9.setText("jLabel1");
        DISPLAY.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 710, 460));

        REMOVE.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RemoveBook.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        REMOVE.getContentPane().add(RemoveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 450, 90));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        REMOVE.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 110, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Type The Book You Want To Remove");
        REMOVE.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton10.setText("Remove");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        REMOVE.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        jLabel11.setText("jLabel1");
        REMOVE.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -320, 1360, 650));

        javax.swing.GroupLayout SORTLayout = new javax.swing.GroupLayout(SORT.getContentPane());
        SORT.getContentPane().setLayout(SORTLayout);
        SORTLayout.setHorizontalGroup(
            SORTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SORTLayout.setVerticalGroup(
            SORTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton1.setText("Add Books");
        jButton1.setToolTipText("");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setInheritsPopupMenu(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 289, 164));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton6.setText("Remove Books");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 289, 164));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton7.setText("Sort Books");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 289, 164));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton8.setText("Exit\n");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 191, 164));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/e.jpg"))); // NOI18N
        jButton9.setText("Display Books");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 289, 164));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 53)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 880, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 190, 1350, 480));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 140, 1340, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image/dark-blue-background-light-beam-vignette-lines-8lwuskc45jsn0xk1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1110, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vecteezy_simple-elegant-blue-background-for-design-waves-empty_33224233.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -7, 970, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Data D = new Data();
    
  private void init() {
     if (D.bookStack.isEmpty()) {
        for (String book : D.books) {
            D.bookStack.push(book);
        }
        for (int i = D.bookStack.size() - 1; i >= 0; i--) {
                DefaultTableModel a = (DefaultTableModel) Table.getModel();

                String book = D.bookStack.get(i);
                a.addRow(new Object[] { book });
    }
  }}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ADD.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        ADD.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        D.bookStack.push(addInput.getText());
        JOptionPane.showMessageDialog(null, addInput.getText() + " added to database.", "Success",  JOptionPane.PLAIN_MESSAGE);
        ADD.setVisible(false);
                DefaultTableModel a = (DefaultTableModel) Table.getModel();

                String book = addInput.getText();
                a.addRow(new Object[] { book });
    }//GEN-LAST:event_addActionPerformed

    private void addInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addInputActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       REMOVE.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (D.bookStack.isEmpty()) {
            JOptionPane.showMessageDialog(null, "There are no books.", "Error",  JOptionPane.PLAIN_MESSAGE);
        } else {
           
                DISPLAY.pack();
                DISPLAY.setVisible(true);
            }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DISPLAY.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel a = (DefaultTableModel) Table.getModel();
        a.setRowCount(0);
         if (D.bookStack.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No books to sort.", "Error",  JOptionPane.PLAIN_MESSAGE);
            return;
        }
        Stack<String> tempStack = new Stack<>();
        while (!D.bookStack.isEmpty()) {
            String temp = D.bookStack.pop();
            while (!tempStack.isEmpty() && tempStack.peek().compareTo(temp) > 0) {
                D.bookStack.push(tempStack.pop());
            }
            tempStack.push(temp);
        }
        D.bookStack = tempStack;
         for (int i = 0 ; i <= D.bookStack.size() - 1; i++) {

                String book = D.bookStack.get(i);
                a.addRow(new Object[] { book });
    }
        JOptionPane.showMessageDialog(null, "Books sorted alphabetically.", "Success",  JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         JOptionPane.showMessageDialog(null, "Thank you for using our program.", "Goodbye.",  JOptionPane.PLAIN_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (D.bookStack.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No books to remove.", "Error",  JOptionPane.PLAIN_MESSAGE);
            return;
        }
        REMOVE.pack();
        REMOVE.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        String compareString = RemoveBook.getText();
        Stack<String> auxStack = new Stack<>();
        while(!D.bookStack.isEmpty()) {
        String st = D.bookStack.pop();
        if(st.compareTo(compareString) != 0)
        auxStack.push(st);
}
JOptionPane.showMessageDialog(null, "Removed book: "+compareString, "Success.",  JOptionPane.PLAIN_MESSAGE);
while(!auxStack.isEmpty()) 
    D.bookStack.push(auxStack.pop());
     DefaultTableModel a = (DefaultTableModel) Table.getModel();
        a.setRowCount(0);
     for (int i = 0 ; i <= D.bookStack.size() - 1; i++) {

                String book = D.bookStack.get(i);
                a.addRow(new Object[] { book });
    }
    REMOVE.setVisible(false);

    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            new Library().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ADD;
    private javax.swing.JFrame DISPLAY;
    private javax.swing.JFrame REMOVE;
    private javax.swing.JTextField RemoveBook;
    private javax.swing.JFrame SORT;
    private javax.swing.JTable Table;
    private javax.swing.JButton add;
    private javax.swing.JTextField addInput;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
